-- Story 1  

insert into messages(id_expediteur, id_receveur, contenu) 
values (1, 2, "Salut"),
(2, 1, "Salut"),
(1, 2, "ça va ?"),
(2, 1, "Bien et toi ?"),
(1, 2, "Bien"),
(2, 1, "ça fait quoi là ?"),
(1, 2, "ça fait des base de données tranquille"),
(2, 1, "Ah ouais je vois"),
(1, 3, "Qu'est ce qui me veut"),
(5, 9, "Je sais pas c'est à qu'elle heure mon prochain rdv"),
(9, 4, "C'était comment ton rdv ?"),
(10, 3, "T'as parlé aux chats de paul ?"),
(2, 1, "Salut"),
(1, 2, "ça va ?"),
(2, 1, "Bien et toi ?"),
(1, 2, "Bien"),
(2, 1, "ça fait quoi là ?"),
(1, 2, "ça fait des base de données tranquille"),
(2, 1, "Ah ouais je vois"),
(1, 3, "Qu'est ce qui me veut"),
(5, 9, "Je sais pas c'est à qu'elle heure mon prochain rdv"),
(9, 4, "C'était comment ton rdv ?"),
(10, 3, "T'as parlé aux chats de paul ?"),
(9, 4, "C'était comment ton rdv ?"),
(10, 3, "T'as parlé aux chats de paul ?"),
